version: '3.8'
services:
  postgres:
    image: postgres:15
    ports:
      - "5434:5432"
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: note-app
    networks:
      - netjs-network
networks:
  netjs-network: